### ISSUE TITLE
HA Dashboard for Fire Tablet 7"

### ISSUE THREAD

**Issue by STUKguy** [pbulteel/home-assistant-examples#20]
If like me you have mistakenly brought a Fire Tablet 7" and cant return it, its pefect for a very basic HA Dashboard tablet. I have tried many differant layouts but this is the only way i have manged to get what i need in one place. The tablet is just too small.

This is what the layout would look like on you computer
![image](https://github.com/pbulteel/home-assistant-examples/assets/66088795/cf7a5624-755a-4305-b19e-7d1caacdcd6b)

This is what the dashboard would look on your tablet (sorry about the glare)
![20240224_222533](https://github.com/pbulteel/home-assistant-examples/assets/66088795/af559ba1-c632-412f-b9f4-1a87f67bd69f)

Here is a link to the yaml
https://gist.github.com/STUKguy/e54c0f0cf5fb3f1307f817675717c259

**Comment by pbulteel** [comment]
Awesome! Thanks for the contribution.
